application: a1lrfid
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.js)
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.png)
  static_files: static/\1
  upload: static/(.*\.png)

- url: .*
  script: main.py
  
